config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
  	resources :comments
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
	
	validates :title, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/postcategory.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(post_params)

		if @comment.save
			flash[:notice] = 'You added your comment'
			redirect_to post_comment_path
		else
			render :new
		end
  end

end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController

	def index
		
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

		@posts = Post.all
			
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
		@post = Post.new(post_params)

		if @post.save
			flash[:notice] = 'You created a post'
			redirect_to root_path
		else
			render :new
		end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])

  	binding.pry
		if @post.save
			flash[:notice] = 'You updated a post'
			redirect_to root_path
		else
			render :new
		end

  end

  def post_params
  	params.require(:post).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<h4>add comment area</h4>
<P>

<%= link_to 'All Posts', root_path %> |
<%= link_to 'Back', posts_path %>	
	

app/views/comments/new.html.erb
<h3>Add a comment to the post</h3>
<p>

<%= form_for @comment do |f| %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	
	<br>
	<%= f.submit "Add Comment" %>

<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'New Post', new_post_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>
	<%= f.submit "Create Post" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<p>

app/views/posts/index.html.erb
<h3>Welcome!</h3>



<table  width=600>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.description %></td>

        <td><%= link_to 'Show Post', post_path(post) %> | </td>
        <td><%= link_to 'Edit Post', edit_post_path(post) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h3>Create a new post </h3>
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>

<%= render 'form' %>



-----------------------------------

<h3>Non-model backed form example</h3>

<%= form_tag '/posts' do %>
	<%= label_tag :title %>
	<%= text_field_tag :title %>
	<br>
	<%= label_tag :url %>
	<%= text_field_tag :url %>
	<br>
	<%= label_tag :description %>
	<%= text_field_tag :description %>
	<br>
	<%= submit_tag "Create Post" %>
<% end %>


<h3>Model backed form exmaple </h3>
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>
	<%= f.submit "Create Post" %>

<% end %>

app/views/posts/show.html.erb
<h4>Viewing Post </h4>
<P>
<%= @post.title %>:  <%= @post.description %>
<p>
<%= link_to 'All Posts', root_path %> | 
<%= link_to 'Add Comment', new_post_comment_path(params[:id]) %>